language: node_js
node_js:
- '6'
script:
- npm run lint
- chmod 777 deploy.sh
- ./deploy.sh
deploy:
  provider: script
  script: ./deploy.sh
  on:
    branch: master
before_install:
- openssl aes-256-cbc -K $encrypted_e62857c60f1c_key -iv $encrypted_e62857c60f1c_iv
  -in deploy.sh.enc -out deploy.sh -d
